pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"
  dotnetSdkVersion: "6.0.x"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: "$(dotnetSdkVersion)"

  - task: DotNetCoreCLI@2
    inputs:
      command: "restore"
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    inputs:
      command: "build"
      arguments: "--no-restore --configuration $(buildConfiguration)"
      projects: "**/*.csproj"
