pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"
  dotnetSdkVersion: "6.0.100"

steps:
  - task: NuGetToolInstaller@1

  - task: NuGetAuthenticate@1

  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: "$(dotnetSdkVersion)"

  - task: DotNetCoreCLI@2
    inputs:
      command: "restore"
      projects: "**/*.csproj"
